#!/usr/bin/env python3
"""Refresh finance-mcp/finance_mcp/data/idx_tickers.txt from IDX.

Hits the same IDX security-master endpoint the `idx` provider uses.
Not run automatically — an operator runs this and commits the diff so
supply-chain drift stays visible. See ADR-0021 §Refresh.

Usage:
    scripts/refresh_idx_tickers.py           # write in place
    scripts/refresh_idx_tickers.py --dry-run # print diff only
"""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path

import httpx


REPO = Path(__file__).resolve().parent.parent
DEST = REPO / "finance-mcp" / "finance_mcp" / "data" / "idx_tickers.txt"

URL = "https://www.idx.co.id/primary/ListedCompany/GetCompanyProfiles"
HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"
    ),
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "en-US,en;q=0.9,id;q=0.8",
    "Referer": "https://www.idx.co.id/",
    "X-Requested-With": "XMLHttpRequest",
}


def fetch() -> list[str]:
    with httpx.Client(headers=HEADERS, timeout=30.0, follow_redirects=True) as c:
        r = c.get(URL, params={"start": 0, "length": 9999, "language": "en-us"})
        r.raise_for_status()
        payload = r.json()
    rows = payload.get("data") or payload.get("Rows") or []
    codes: set[str] = set()
    for row in rows:
        code = str(row.get("KodeEmiten") or row.get("Code") or "").strip().upper()
        if len(code) == 4 and code.isalpha():
            codes.add(code)
    return sorted(codes)


def render(codes: list[str]) -> str:
    header = (
        "# IDX ticker allowlist. Auto-generated by scripts/refresh_idx_tickers.py.\n"
        "# One ticker per line, 4-letter IDX standard, uppercase.\n"
        "# Refresh + commit diff when new listings appear.\n\n"
    )
    return header + "\n".join(codes) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    try:
        codes = fetch()
    except Exception as e:
        print(f"refresh failed: {e}", file=sys.stderr)
        return 1
    if not codes:
        print("no codes returned; aborting", file=sys.stderr)
        return 2

    body = render(codes)
    if args.dry_run:
        sys.stdout.write(body)
        return 0

    DEST.write_text(body, encoding="utf-8")
    print(f"wrote {len(codes)} tickers to {DEST.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
